# This file configures the pre-commit hooks that run on every `git commit`.

repos:
  - repo: local
    hooks:
      - id: ruff-lint
        name: "Lint with Ruff"
        entry: poetry run ruff check . --fix --exit-non-zero-on-fix
        language: system
        types: [python]

      - id: ruff-format
        name: "Format with Ruff"
        entry: poetry run ruff format .
        language: system
        types: [python]
