from typing import Any, Self

class YoutubeDL:
    def __init__(
        self, params: dict[str, Any] | None = ..., auto_init: bool = ...
    ) -> None: ...
    def download(self, url_list: list[str]) -> int: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: Any) -> None: ...
